export const ServiceData = [
  {
    id: 1,
    category: 'automotive-services',
    title: 'Routine Maintenance',
    subTitle: 'Keep Your Vehicle in Excellent Condition',
    image: '/images/maintain.jpg',
    aboutService: 'Oil changes, tire rotations, and brake pad replacements to ensure your vehicle runs smoothly.',
    wPoint1: 'Extend the life of your vehicle',
    wPoint2: 'Maintain optimal performance',
    wPoint3: 'Ensure safety and reliability',
    hPoint1: 'Affordable and efficient service',
    hPoint2: 'Experienced technicians at your service',
    hPoint3: 'Regular maintenance prevents costly repairs',
    desc: 'Keep your vehicle in top shape with our routine maintenance services, designed to prevent costly repairs and extend the life of your car.'
  },
  {
    id: 2,
    category: 'automotive-services',
    title: 'Auto Repairs',
    subTitle: 'Get Your Car Back on the Road Quickly',
    image: '/images/reapair.jpg',
    aboutService: 'From engine overhauls to transmission replacements, we handle all major and minor repairs.',
    wPoint1: 'Comprehensive repair solutions',
    wPoint2: 'Quick turnaround times',
    wPoint3: 'High-quality replacement parts',
    hPoint1: 'Experienced mechanics for complex repairs',
    hPoint2: 'Transparent pricing and detailed estimates',
    hPoint3: 'Restore your vehicle to peak condition',
    desc: 'Our skilled technicians provide fast and reliable auto repairs, ensuring your vehicle is running smoothly and safely.'
  },
  {
    id: 3,
    category: 'automotive-services',
    title: 'Briefly Inspections',
    subTitle: 'Identify Potential Issues Before They Become Major Problems',
    image: '/images/inspection.jpg',
    aboutService: 'Comprehensive vehicle inspections to ensure everything is in optimal working condition.',
    wPoint1: 'Thorough examination of your vehicle',
    wPoint2: 'Identify hidden issues',
    wPoint3: 'Peace of mind for drivers',
    hPoint1: 'Prevent unexpected breakdowns',
    hPoint2: 'Ensure compliance with safety standards',
    hPoint3: 'Expert advice on necessary repairs',
    desc:'Our detailed inspections catch potential issues early, ensuring your vehicle’s performance and safety are always at their best.',

  },
  {
    id: 4,
    category: 'automotive-services',
    title: 'Best Customization',
    subTitle: 'Enhance Your Vehicle\'s Performance and Appearance',
    image: '/images/customize.jpg',
    aboutService: 'Personalize your vehicle with performance upgrades and aesthetic modifications.',
    wPoint1: 'Tailored solutions for your needs',
    wPoint2: 'High-quality customization options',
    wPoint3: 'Expert installation by professionals',
    hPoint1: 'Boost performance and efficiency',
    hPoint2: 'Stand out with a unique look',
    hPoint3: 'Increase the value of your vehicle',
    desc:'Transform your ride with our top-tier customization services, tailored to enhance both performance and style to suit your unique preferences.'
  },
//   {
//     id: 'language-courses',
//     category:'courses',
//     title: 'Language Courses',
//     image: "/images/language.svg",
//   },
// {
//   id: 'computer-courses',
//   category:'courses',
//   title: "Computer Courses",
//   image: "/images/computer.svg",
// },
// {
//   id: 'tution-courses',
//   category:'courses',
//   title: 'Tuition Courses',
//   image: "/images/tution.svg",
// },

]